# Generated by Django 6.0.7 on 2026-07-22 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resumeanalysis",
            name="improvements",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="resumeanalysis",
            name="interview_questions",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="resumeanalysis",
            name="missing_skills",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="resumeanalysis",
            name="strengths",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
