# Generated by Django 6.0.5 on 2026-09-01 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_services", "0006_resumeanalysis"),
    ]

    operations = [
        migrations.AddField(
            model_name="resumeanalysis",
            name="resume_file",
            field=models.FileField(blank=True, null=True, upload_to="resumes/"),
        ),
    ]
